apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.configmapName }}
  labels:
    app: liqo.io
data:
  clusterID: "placeHolder"
  podCIDR: {{ .Values.podCIDR }}
  serviceCIDR: {{ .Values.serviceCIDR }}
  gatewayPrivateIP: "192.168.1.1" #placeholder, needed by broadcaster. soon will be removed
  gatewayIP: "placeholder"