apiVersion: v1
kind: ServiceAccount
metadata:
  name: tunnelendpointcreator-operator-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: tunnelendpointcreator-manager-role
rules:
- apiGroups:
  - liqonet.liqo.io
  resources:
  - tunnelendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - liqonet.liqo.io
  resources:
  - tunnelendpoints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - protocol.liqo.io
  resources:
  - advertisements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - protocol.liqo.io
  resources:
  - advertisements/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
    - policy.liqo.io
  resources:
    - clusterconfigs
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tunnelendpointcreator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tunnelendpointcreator-manager-role
subjects:
  - kind: ServiceAccount
    name: tunnelendpointcreator-operator-service-account
    namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: tunnelendpointcreator-operator
  name: tunnelendpointcreator-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tunnelendpointcreator-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: tunnelendpointcreator-operator
    spec:
      serviceAccountName: tunnelendpointcreator-operator-service-account
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-node
      containers:
        - image: {{ .Values.image.repository }}{{ .Values.global.suffix | default .Values.suffix }}:{{ .Values.global.version | default .Values.version }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: tunnelendpointcreator-operator
          command: ["/usr/bin/liqonet"]
          args:
            - "-run-as=tunnelEndpointCreator-operator"
      restartPolicy: Always
status: {}
